### ISSUE TITLE
examples in lessons/Solution, Basic Practice.md have cy.get('form').submit();

### ISSUE THREAD

**Issue by harkinj** [stevekinney/cypress-examples#8]
Hi,
Any reason why most examples in lessons/Solution, Basic Practice.md have
cy.get('form').submit();
rather than actually clicking button to submit the form?

I'd expect clicking button to be done as that is what user does to submit the form.
Thanks for all info.
John

**Comment by UzaeirAzhar** [comment]
@harkinj  For submitting a form its a good practice to use `submit` instead of `click`.  Here is the link from the official documentation for more reference: https://docs.cypress.io/api/commands/submit#docusaurus_skipToContent_fallback

**Comment by stevekinney** [comment]
Yup, @UzaeirAzhar is right!
